### ISSUE TITLE
Investigate integration to Oracle Blockchain Platform

### ISSUE THREAD

**Issue by imacoindev** [EspeoBlockchain/gardener-server#65]
So far it seems that Oracle does not have a SGX integration in their Blockchain Platform. We should look into what are the benefits that we can offer to them by integrating Gardener to their platform.

Think of this in terms of:
- Oracle's core business is selling database licenses and hosting to enterprises.
- They have a PaaS Blockchain Platform that uses Fabric to allow their clients to have business logic on top of their stored data. This allows to automate business processes and create innovative solutions.
- Oracle's clients come from all possible industries.
- For example, their client uses MySQL to store their supply chain data. They want to build an automation to their workflow by implementing chain code that automates a large chunk of their process and removes risk for errors when people make entries manually across the supply chain. 

- How can Gardener improve the security of their Blockchain Platform and benefit their clients. For example, if they don't have remote attestation and sealing implemented, how would that benefit them and their clients?

More details of their platform can be found in:
https://www.oracle.com/application-development/cloud-services/blockchain-platform/

**Comment by kss-espeo** [comment]
They mention an `Oracle-added REST proxy` in their documentation. I would imagine this is the tool that they use to get data from 3rd party REST services to their chaincode. A use case for Gardener would be replacing that tool. It's hard to say how is their tool different from Gardener because I was not able to find much information about it, but anyway here's a list that could be more accurate if I had more info on their `Oracle-added REST proxy`:

More datasources - apart from REST datasources we also have random and more in the future
Fault resistance - if any part of Gardener goes down, all the Oracle requests are persisted in a database and will be resumed once system is back up
For some of the use cases (RNG mostly) we secure our process with SGX, so that a party that hosts Oracle is not a Third Trusted Party. Probably this is not such a huge deal, since Oracle hosts their stuff themselves and even if Oracle would not be a TTP for their clients for Oracle processes, it will remain TTP because for example it also hosts Fabric nodes.
